ktor:
    application:
        modules:
            - J.dev.ApplicationKt.module
            - J.dev.Individuals.IndividualRoutesKt.IndividualRoutes
    deployment:
      port: 8080
      host: localhost #192.168.50.237
postgres:
  url: "jdbc:postgresql://localhost:5432/kotlinscheduler"
  user: postgres
  password: 1234